app:
  build: .
  ports:
    - "80"
  volumes:
    - .:/site/app
    - ./docker:/docker
    - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled
    # - ~/.composer:/root/.composer
    - ./.zsh_history:/root/.zsh_history
  environment:
    - VIRTUAL_HOST=yoursite.docker
    - VIRTUAL_PORT=80
  links:
    - mysql
  log_opt:
    max-size: 50k

mysql:
  image: mysql:latest
  environment:
    - VIRTUAL_HOST=mysql.yoursite.docker
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=your_database
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
  log_opt:
    max-size: 50k
  volumes:
    - ./docker/mysql:/var/lib/mysql

# vim:set ts=2 sw=2 smarttab: